### PR TITLE
Adds allowed file extensions accepted

### PR DESCRIPTION
**Pull request by tauil**
Item from [this card](https://trello.com/c/FHpoGeMd/381-3-1-fixes)
## Preview:

screen shot 2015-06-30 at 12 46 13

### CODE REVIEW

**Comment by rodrigotassinari** [comment]
This info should be (also) on the uploads part. That's the most important part, because that's what the API user will read first in order to send files to Rexpense.

**Comment by tauil** [comment]
Ok

**Comment by tauil** [comment]
Done

**Comment by rodrigotassinari** [comment]
:+1:

**Pull request merged**
